# Generated by Django 3.0.1 on 2019-12-30 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('published_year', models.DateField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Band_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Music_Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50)),
                ('established_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bands.Album')),
                ('artist', models.ManyToManyField(to='bands.Band_member')),
                ('gener', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bands.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='band_member',
            name='role',
            field=models.ManyToManyField(to='bands.Role'),
        ),
        migrations.AddField(
            model_name='album',
            name='music_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bands.Music_Band'),
        ),
    ]
