# Generated by Django 3.0.1 on 2020-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_auto_20200107_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
