# Generated by Django 3.0.1 on 2020-01-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_auto_20200108_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmember',
            name='status',
        ),
        migrations.AddField(
            model_name='bandmember',
            name='joined_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bandmember',
            name='musical_band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='bands.MusicalBand'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MemberStatus',
        ),
    ]
