# Generated by Django 3.0.1 on 2020-01-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_auto_20200109_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
