# Generated by Django 3.0.1 on 2020-01-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_bandmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='musicalband',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
