# Generated by Django 3.0.1 on 2020-01-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0010_auto_20200128_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
